"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { clipExternalJob, deleteWorkspace, listWorkspace } from "@/lib/productWorkspace";

type Job = Record<string, unknown> & { id?: string };
export default function SavedJobsPage() {
  const [jobs, setJobs] = useState<Job[]>([]);
  const [loading, setLoading] = useState(true);
  const [url, setUrl] = useState("");
  const [clipTitle, setClipTitle] = useState("");
  const [clipCompany, setClipCompany] = useState("");
  useEffect(() => { listWorkspace("saved-jobs").then(setJobs).catch(() => undefined).finally(() => setLoading(false)); }, []);
  async function remove(id: string) { await deleteWorkspace("saved-jobs", id).catch(() => undefined); setJobs((items) => items.filter((item) => item.id !== id)); }
  async function clip() { if (!url.trim()) return; const item = await clipExternalJob({ url: url.trim(), title: clipTitle || "Captured opportunity", company: clipCompany }); setJobs((items) => [item, ...items]); setUrl(""); setClipTitle(""); setClipCompany(""); }
  return <AppShell><main className="min-h-screen p-5 text-white md:p-8"><div className="mx-auto max-w-7xl"><header className="border-b border-white/10 pb-6"><p className="text-xs uppercase tracking-[0.2em] text-white/60">Opportunity memory</p><h1 className="mt-2 text-4xl font-semibold">Saved Jobs</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/70">Persist canonical opportunities, source provenance, notes and external captures across sessions.</p></header><section className="mt-6 rounded-3xl border border-white/10 bg-white/[0.025] p-5"><div className="text-sm font-semibold">Browser clipper workflow</div><div className="mt-3 grid gap-3 md:grid-cols-3"><input value={url} onChange={(e)=>setUrl(e.target.value)} placeholder="https://company.com/jobs/..." className="rounded-xl border border-white/10 bg-black/10 px-3 py-3 text-sm"/><input value={clipTitle} onChange={(e)=>setClipTitle(e.target.value)} placeholder="Role title" className="rounded-xl border border-white/10 bg-black/10 px-3 py-3 text-sm"/><input value={clipCompany} onChange={(e)=>setClipCompany(e.target.value)} placeholder="Company" className="rounded-xl border border-white/10 bg-black/10 px-3 py-3 text-sm"/></div><button type="button" onClick={()=>void clip()} className="mt-3 rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-black">Capture external job</button></section><div className="mt-6 grid gap-4">{loading ? <p className="text-sm text-white/50">Loading saved jobs…</p> : jobs.length ? jobs.map((job) => <article key={String(job.id)} className="rounded-3xl border border-white/10 bg-white/[0.025] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">{String(job.title ?? "Untitled role")}</h2><p className="mt-1 text-sm text-white/65">{String(job.company ?? "Company not listed")}</p><p className="mt-2 text-xs text-white/45">{Array.isArray(job.location) ? job.location.join(" · ") : String(job.location ?? "Location unspecified")}</p></div><div className="flex gap-2"><Link href="/applications" className="rounded-xl border border-white/10 px-3 py-2 text-xs">Track</Link><button type="button" onClick={() => job.id && void remove(job.id)} className="rounded-xl border border-red-400/15 px-3 py-2 text-xs text-red-200">Remove</button></div></div>{typeof job.explanation === "string" && <p className="mt-4 text-sm leading-6 text-white/60">{job.explanation}</p>}</article>) : <div className="rounded-3xl border border-dashed border-white/10 p-8 text-sm text-white/50">No saved jobs yet. Search opportunities or use the browser-clipper workflow.</div>}</div></div></main></AppShell>;
}
