"use client";
import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { listWorkspace, saveWorkspace } from "@/lib/productWorkspace";

type Contact = Record<string, unknown> & { id?: string };
export default function NetworkingPage() {
  const [items, setItems] = useState<Contact[]>([]);
  const [name, setName] = useState(""); const [company, setCompany] = useState(""); const [status, setStatus] = useState("Prospect"); const [notes, setNotes] = useState("");
  useEffect(() => { listWorkspace("networking").then(setItems).catch(() => undefined); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); const item = await saveWorkspace("networking", { name, company, status, notes, updated_at: new Date().toISOString() }); setItems((current) => [item, ...current]); setName(""); setCompany(""); setNotes(""); }
  return <AppShell><main className="min-h-screen p-5 text-white md:p-8"><div className="mx-auto max-w-6xl"><header className="border-b border-white/10 pb-6"><p className="text-xs uppercase tracking-[0.2em] text-white/60">Relationship intelligence</p><h1 className="mt-2 text-4xl font-semibold">Networking CRM</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/70">Track relationships, status, follow-ups and interaction memory without mixing contacts between users.</p></header><form onSubmit={submit} className="mt-6 grid gap-3 rounded-3xl border border-white/10 bg-white/[0.025] p-5 md:grid-cols-4"><input required value={name} onChange={(e)=>setName(e.target.value)} placeholder="Contact name" className="rounded-xl border border-white/10 bg-black/10 px-3 py-3 text-sm outline-none"/><input value={company} onChange={(e)=>setCompany(e.target.value)} placeholder="Company" className="rounded-xl border border-white/10 bg-black/10 px-3 py-3 text-sm outline-none"/><select value={status} onChange={(e)=>setStatus(e.target.value)} className="rounded-xl border border-white/10 bg-black/10 px-3 py-3 text-sm outline-none"><option>Prospect</option><option>Contacted</option><option>Active relationship</option><option>Follow-up</option></select><input value={notes} onChange={(e)=>setNotes(e.target.value)} placeholder="Notes" className="rounded-xl border border-white/10 bg-black/10 px-3 py-3 text-sm outline-none"/><button className="rounded-xl bg-white px-4 py-3 text-xs font-semibold text-black md:col-span-4">Add contact</button></form><div className="mt-6 grid gap-4 md:grid-cols-2">{items.map((item)=><article key={String(item.id)} className="rounded-3xl border border-white/10 bg-white/[0.025] p-5"><div className="flex items-center justify-between gap-3"><div className="font-semibold">{String(item.name)}</div><span className="rounded-full border border-white/10 px-2.5 py-1 text-[11px] text-white/60">{String(item.status)}</span></div><div className="mt-1 text-sm text-white/60">{String(item.company || "Independent")}</div><p className="mt-4 text-sm leading-6 text-white/60">{String(item.notes || "No notes yet.")}</p></article>)}</div></div></main></AppShell>;
}
